export const tabletsData = [
  {
    id: 1,
    name: "iPad Pro 12.9-inch",
    price: 1299,
    imageUrl: "https://picsum.photos/200/300?image=1065",
    brand: "Apple",
    displaySize: 12.9,
    storageCapacity: 128,
    operatingSystem: "iPadOS",
    cameraResolution: "12MP",
    batteryCapacity: 7590,
  },
  {
    id: 2,
    name: "Samsung Galaxy Tab S8 Ultra",
    price: 1199,
    imageUrl: "https://picsum.photos/200/300?image=1066",
    brand: "Samsung",
    displaySize: 14.6,
    storageCapacity: 128,
    operatingSystem: "Android",
    cameraResolution: "13MP",
    batteryCapacity: 11200,
  },
  {
    id: 3,
    name: "Lenovo Tab P12 Pro",
    price: 899,
    imageUrl: "https://picsum.photos/200/300?image=1067",
    brand: "Lenovo",
    displaySize: 12.6,
    storageCapacity: 128,
    operatingSystem: "Android",
    cameraResolution: "8MP",
    batteryCapacity: 10200,
  },
  {
    id: 4,
    name: "Microsoft Surface Go 3",
    price: 599,
    imageUrl: "https://picsum.photos/200/300?image=1068",
    brand: "Microsoft",
    displaySize: 10.5,
    storageCapacity: 64,
    operatingSystem: "Windows 11",
    cameraResolution: "5MP",
    batteryCapacity: 4500,
  },
  {
    id: 5,
    name: "Amazon Fire HD 10 Plus",
    price: 249,
    imageUrl: "https://picsum.photos/200/300?image=1069",
    brand: "Amazon",
    displaySize: 10.1,
    storageCapacity: 32,
    operatingSystem: "Fire OS",
    cameraResolution: "5MP",
    batteryCapacity: 7600,
  },
  {
    id: 6,
    name: "TCL Tab 10s",
    price: 199,
    imageUrl: "https://picsum.photos/200/300?image=1070",
    brand: "TCL",
    displaySize: 10.1,
    storageCapacity: 32,
    operatingSystem: "Android",
    cameraResolution: "8MP",
    batteryCapacity: 8000,
  },
  {
    id: 7,
    name: "Acer Chromebook Spin 713",
    price: 399,
    imageUrl: "https://picsum.photos/200/300?image=1071",
    brand: "Acer",
    displaySize: 13.5,
    storageCapacity: 64,
    operatingSystem: "Chrome OS",
    cameraResolution: "8MP",
    batteryCapacity: 5120,
  },
  {
    id: 8,
    name: "Huawei MatePad Pro 11",
    price: 599,
    imageUrl: "https://picsum.photos/200/300?image=1072",
    brand: "Huawei",
    displaySize: 11.2,
    storageCapacity: 128,
    operatingSystem: "HarmonyOS",
    cameraResolution: "13MP",
    batteryCapacity: 8300,
  },
];
